### ISSUE TITLE
Button click event not triggering the expected actions in DevRev snap-in

### ISSUE THREAD

**Issue by sourabh-kulkarni-unskript** [devrev/snap-in-examples#50]
I’m a beginner working with the DevRev snap-in example from the repository. I created a timeline entry based on the `work_created` event, which consist of a button. I need to capture the button click event and perform certain actions based on it. However, something seems to be missing or misconfigured.

Here are the steps I followed:

1. I have two functions defined in the `manifest.yaml`, `function_1` and `function_2`. `function_1` is used to create a timeline entry, and `function_2` is for adding a comment to the timeline. Also I have defined the `snap_kit_actions` as:
```
functions:
  - name: function_1
    description: Function to create a timeline entry
  - name: function_2
    description: Function to create a timeline entry comment on a DevRev work item on which comment is added.

automations:
  - name: convergence_automation_devrev
    source: devrev-webhook
    event_types:
      - work_created
    function: function_1

snap_kit_actions:
  - name: button_action
    function: function_1
    description: Test button action
```

2. In `function_1`, I am attempting to capture the `work_created` event and include a button (`My Button`) in the timeline entry:
```
 async function handleEvent(event: any) {
  const devrevPAT = event.context.secrets.service_account_token;
  const API_BASE = event.execution_metadata.devrev_endpoint;
  const devrevSDK = client.setup({
    endpoint: API_BASE,
    token: devrevPAT,
  });
  const workCreated = event.payload.work_created.work;

  let bodyComment =
  'This is a test comment';

  const body = {
    object: workCreated.id,
    type: "timeline_comment",
    body: bodyComment,
    body_type: "text",
    snap_kit_body: {
      snap_in_action_name: "button_action",
      body: {
        snaps: [
          {
            elements: [
              {
                direction: "row",
                elements: [
                  {
                    action_id: "my_button",
                    action_type: "remote",
                    style: "destructive",
                    text: {
                      text: "My Button",
                      type: "plain_text",
                    },
                    type: "button",
                    value: "my_button",
                  },
                ],
                type: "actions",
              },
            ],
            type: "card",
          },
        ],
      },
    },
  };

  try {
    const response = await devrevSDK.timelineEntriesCreate(body as any);
    return response;
  } catch (error) {
    console.error("Error occurred while creating timeline entry:", error);
    throw error;
  }
}

export const run = async (events: any[]) => {
  for (let event of events) {
    try {
      console.log('events: ', JSON.stringify(events));
    } catch (error) {
      console.error("Error processing event:", error);
    }
  }

  const input = events[0]
  const action = input.execution_metadata.event_type

  if (action === 'work_created'){
    await handleEvent(input);
  } 
};

export default run;

```

So, it is expected that when user clicks the button `My Button` (created as a timeline entry when work item is created) the event should get triggered and this event should get captured and create another timeline entry based on that event.

But current the behaviour is, when user clicks the button `My Button` a pop-up is shown at the bottom left corner as `Something went wrong`. I checked the logs by running the command:
```
devrev snap_in_package logs --after "2025-02-19T00:00:00Z" --filters '{"process": {"values": ["function"]}}' | jq
```
where I don't see any error logged. 

Can someone guide me on what I might be missing or misconfiguring? What could be causing the issue where the button click doesn't trigger the expected action?
